apiVersion: v2
name: nfs-server-bci
description: A lightweight, containerized NFS server for Harvester/SLE Micro using SLE BCI.
type: application
version: 1.0.5
appVersion: "16.0-20260206"
maintainers:
  - name: Erico Mendonca (erico.mendonca@suse.com)
