apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-server-bci-csi
provisioner: nfs.csi.k8s.io
parameters:
  # IP of the Harvester Node running your NFS Pod
  server: 192.168.1.50 
  share: /data
  # Create a subfolder for every PVC automatically
  subDir: ${pvc.metadata.namespace}/${pvc.metadata.name}
  mountPermissions: "0777"
reclaimPolicy: Delete
volumeBindingMode: Immediate
mountOptions:
  - nfsvers=4.1
allowVolumeExpansion: true
