apiVersion: v1
kind: Pod
metadata:
  name: nfs-test-pod
spec:
  containers:
  - name: busybox
    image: registry.suse.com/bci/bci-busybox
    command: ["/bin/sh", "-c", "echo 'Hello from Harvester Storage' > /mnt/data/hello.txt; sleep 3600"]
    volumeMounts:
    - name: nfs-pvc
      mountPath: "/mnt/data"
  volumes:
  - name: nfs-pvc
    persistentVolumeClaim:
      claimName: test-dynamic-claim