apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-dynamic-claim
  namespace: default
spec:
  accessModes:
    - ReadWriteMany  # The superpower of NFS
  storageClassName: nfs-server-bci-csi
  resources:
    requests:
      storage: 5Gi