apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "nfs-server-bci.fullname" . }}
  labels:
    {{- include "nfs-server-bci.labels" . | nindent 4 }}
spec:
  replicas: 1
  strategy:
    type: Recreate # Important: Don't run two servers at once on same host path
  selector:
    matchLabels:
      {{- include "nfs-server-bci.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "nfs-server-bci.selectorLabels" . | nindent 8 }}
    spec:
      {{- if .Values.hostNetwork }}
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      {{- end }}
      
      nodeSelector:
        {{- toYaml .Values.nodeSelector | nindent 8 }}
      
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}

          env:
            - name: SHARED_DIRECTORY
              value: {{ .Values.nfs.exportPath | quote }}
            - name: ALLOWED_CLIENTS
              value: {{ .Values.nfs.allowedClients | quote }}
            - name: EXPORT_OPTIONS
              value: {{ .Values.nfs.exportOptions | quote }}
            - name: NODE_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP

          # Ports are for documentation when hostNetwork is true
          ports:
            - name: nfs
              containerPort: 2049
              protocol: TCP
            - name: mountd
              containerPort: 20048
              protocol: TCP
            - name: rpcbind
              containerPort: 111
              protocol: TCP

          volumeMounts:
            - name: data
              mountPath: {{ .Values.nfs.exportPath }}
          
          resources:
            {{- toYaml .Values.resources | nindent 12 }}

      volumes:
        - name: data
          hostPath:
            path: {{ .Values.persistence.hostPath }}
            type: {{ .Values.persistence.type }}
